# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - schmidpaul@hotmail.de
    on_success: never # default: change
    on_failure: never # default: always
